basePath: /
host: covid19-go-deploy.herokuapp.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: |-
    This is a covid19 cases data server which when given the GPS coordinates of a location returns
    the cases details as in confirmed, deceased, recovered, teseted along with vaccination details as in
    single and double dose in coordinates provided State and in India in total
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Covid19 Cases and Vaccinations in India
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /cases:
    get:
      consumes:
      - '*/*'
      description: Get the covid19 cases details for the given GPS coordinates.
      parameters:
      - description: Latitude
        in: query
        name: latitude
        required: true
        type: number
      - description: Longitude
        in: query
        name: longitude
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get latest covid19 cases.
      tags:
      - cases
schemes:
- https
swagger: "2.0"
